---
root: true
ignorePatterns:
  - "**/lib/**"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 6
  sourceType: module
  project:
    - "./tsconfig.eslint.json"
plugins:
  - "@typescript-eslint"
  - import
  - mocha
  - simple-import-sort
  - unused-imports
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:mocha/recommended
  - plugin:unicorn/recommended
rules:
  simple-import-sort/imports: error
  simple-import-sort/exports: error
  sort-imports: 'off'
  import/order: 'off'
  unused-imports/no-unused-imports: error
  no-multiple-empty-lines:
    - warn
    - max: 1
  "@typescript-eslint/explicit-module-boundary-types":
    - error
    - allowHigherOrderFunctions: true
  indent: 'off'
  "@typescript-eslint/indent":
    - error
    - 4
    - MemberExpression: 'off'
      SwitchCase: 1
  quotes: 'off'
  "@typescript-eslint/quotes":
    - error
    - single
    - allowTemplateLiterals: true
      avoidEscape: true
  "@typescript-eslint/no-explicit-any": 'off'
  "@typescript-eslint/no-unused-vars":
    - warn
    - args: none
      vars: all
      varsIgnorePattern: "^.*_$"
  mocha/no-exclusive-tests: 'error'
  mocha/no-mocha-arrows: 'off'
  mocha/no-setup-in-describe: 'off'
  unicorn/empty-brace-spaces: 'off'
  unicorn/filename-case:
    - error
    - cases:
        kebabCase: true
        pascalCase: true
        camelCase: true
  unicorn/import-style:
    - error
    - styles:
        path: false
  unicorn/no-array-for-each: 'off'
  unicorn/no-array-reduce: 'off'
  unicorn/no-array-callback-reference: 'off'
  unicorn/no-null: 'off'
  unicorn/no-static-only-class: 'off'
  unicorn/numeric-separators-style: 'off'
  unicorn/prefer-array-flat: 'off'
  unicorn/prefer-object-from-entries: 'off'
  unicorn/prefer-module: 'off'
  unicorn/prefer-node-protocol: 'off'
  unicorn/prefer-spread: 'off'
  unicorn/prevent-abbreviations:
    - error
    - allowList:
        acc: true
        args: true
        i: true
