extends: '@istanbuljs/nyc-config-typescript'
all: true
include:
  - 'src'
exclude:
  - '**/src/**/*.d.ts'
  - '**/src/types/**'
  - '**/lib/**'
  - '**/spec/**'
  - '**/node_modules/**'
reporter:
  - json
  - text
