language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '12'
  - '10'
  - '8'
script: npm run verify
after_success:
  - npm run travis-deploy-once "npm run doc"
  - npm run travis-deploy-once "npm run publish:reports"
  - npm run travis-deploy-once "npm run publish:site"
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
