window.esdocSearchIndex = [
  [
    "",
    "test-file/spec/match.spec.ts.html#lineNumber6",
    "",
    "test"
  ],
  [
    "",
    "test-file/spec/match.spec.ts.html#lineNumber57",
    " ",
    "test"
  ],
  [
    "",
    "test-file/spec/match.spec.ts.html#lineNumber50",
    " ",
    "test"
  ],
  [
    "tiny-types/lib/pattern-matching/identitymatcher~identitymatcher",
    "class/src/pattern-matching/IdentityMatcher.ts~IdentityMatcher.html",
    "<span>IdentityMatcher</span> <span class=\"search-result-import-path\">tiny-types/lib/pattern-matching/IdentityMatcher</span>",
    "class"
  ],
  [
    "tiny-types/lib/pattern-matching/rules/matcherrule~matcherrule",
    "class/src/pattern-matching/rules/MatcherRule.ts~MatcherRule.html",
    "<span>MatcherRule</span> <span class=\"search-result-import-path\">tiny-types/lib/pattern-matching/rules/MatcherRule</span>",
    "class"
  ],
  [
    "tiny-types/lib/pattern-matching/rules/matchesanything~matchesanything",
    "class/src/pattern-matching/rules/MatchesAnything.ts~MatchesAnything.html",
    "<span>MatchesAnything</span> <span class=\"search-result-import-path\">tiny-types/lib/pattern-matching/rules/MatchesAnything</span>",
    "class"
  ],
  [
    "tiny-types/lib/pattern-matching/rules/matchesequaltinytype~matchesequaltinytype",
    "class/src/pattern-matching/rules/MatchesEqualTinyType.ts~MatchesEqualTinyType.html",
    "<span>MatchesEqualTinyType</span> <span class=\"search-result-import-path\">tiny-types/lib/pattern-matching/rules/MatchesEqualTinyType</span>",
    "class"
  ],
  [
    "tiny-types/lib/pattern-matching/rules/matchesidentical~matchesidentical",
    "class/src/pattern-matching/rules/MatchesIdentical.ts~MatchesIdentical.html",
    "<span>MatchesIdentical</span> <span class=\"search-result-import-path\">tiny-types/lib/pattern-matching/rules/MatchesIdentical</span>",
    "class"
  ],
  [
    "tiny-types/lib/pattern-matching/rules/matchesobjectswithcommonprototype~matchesobjectswithcommonprototype",
    "class/src/pattern-matching/rules/MatchesObjectsWithCommonPrototype.ts~MatchesObjectsWithCommonPrototype.html",
    "<span>MatchesObjectsWithCommonPrototype</span> <span class=\"search-result-import-path\">tiny-types/lib/pattern-matching/rules/MatchesObjectsWithCommonPrototype</span>",
    "class"
  ],
  [
    "tiny-types/lib/pattern-matching/rules/matchesregexp~matchesregexp",
    "class/src/pattern-matching/rules/MatchesRegExp.ts~MatchesRegExp.html",
    "<span>MatchesRegExp</span> <span class=\"search-result-import-path\">tiny-types/lib/pattern-matching/rules/MatchesRegExp</span>",
    "class"
  ],
  [
    "tiny-types/lib/pattern-matching/objectmatcher~objectmatcher",
    "class/src/pattern-matching/ObjectMatcher.ts~ObjectMatcher.html",
    "<span>ObjectMatcher</span> <span class=\"search-result-import-path\">tiny-types/lib/pattern-matching/ObjectMatcher</span>",
    "class"
  ],
  [
    "tiny-types/lib/pattern-matching/patternmatcher~patternmatcher",
    "class/src/pattern-matching/PatternMatcher.ts~PatternMatcher.html",
    "<span>PatternMatcher</span> <span class=\"search-result-import-path\">tiny-types/lib/pattern-matching/PatternMatcher</span>",
    "class"
  ],
  [
    "tiny-types/lib/pattern-matching/stringmatcher~stringmatcher",
    "class/src/pattern-matching/StringMatcher.ts~StringMatcher.html",
    "<span>StringMatcher</span> <span class=\"search-result-import-path\">tiny-types/lib/pattern-matching/StringMatcher</span>",
    "class"
  ],
  [
    "tiny-types/lib/tinytype~tinytype",
    "class/src/TinyType.ts~TinyType.html",
    "<span>TinyType</span> <span class=\"search-result-import-path\">tiny-types/lib/TinyType</span>",
    "class"
  ],
  [
    "tiny-types/lib/tinytype~tinytypeof",
    "function/index.html#static-function-TinyTypeOf",
    "<span>TinyTypeOf</span> <span class=\"search-result-import-path\">tiny-types/lib/TinyType</span>",
    "function"
  ],
  [
    "tiny-types/lib/match~match",
    "function/index.html#static-function-match",
    "<span>match</span> <span class=\"search-result-import-path\">tiny-types/lib/match</span>",
    "function"
  ],
  [
    "",
    "test-file/spec/pattern-matching/IdentityMatcher.spec.ts.html#lineNumber5",
    "IdentityMatcher",
    "test"
  ],
  [
    "",
    "test-file/spec/pattern-matching/IdentityMatcher.spec.ts.html#lineNumber22",
    "IdentityMatcher matches a symbol",
    "test"
  ],
  [
    "",
    "test-file/spec/json.spec.ts.html#lineNumber2",
    "JSON",
    "test"
  ],
  [
    "",
    "test-file/spec/json.spec.ts.html#lineNumber4",
    "JSON JSONArray",
    "test"
  ],
  [
    "",
    "test-file/spec/json.spec.ts.html#lineNumber5",
    "JSON JSONArray ",
    "test"
  ],
  [
    "",
    "test-file/spec/json.spec.ts.html#lineNumber9",
    "JSON JSONObject",
    "test"
  ],
  [
    "",
    "test-file/spec/json.spec.ts.html#lineNumber10",
    "JSON JSONObject ",
    "test"
  ],
  [
    "",
    "test-file/spec/json.spec.ts.html#lineNumber20",
    "JSON JSONPrimitive",
    "test"
  ],
  [
    "",
    "test-file/spec/json.spec.ts.html#lineNumber21",
    "JSON JSONPrimitive ",
    "test"
  ],
  [
    "",
    "test-file/spec/json.spec.ts.html#lineNumber25",
    "JSON JSONValue",
    "test"
  ],
  [
    "",
    "test-file/spec/json.spec.ts.html#lineNumber26",
    "JSON JSONValue describes any value that can be represented as JSON",
    "test"
  ],
  [
    "",
    "test-file/spec/pattern-matching/rules/MatchesAnything.spec.ts.html#lineNumber5",
    "MatchesAnything",
    "test"
  ],
  [
    "",
    "test-file/spec/pattern-matching/ObjectMatcher.spec.ts.html#lineNumber6",
    "ObjectMatcher",
    "test"
  ],
  [
    "",
    "test-file/spec/pattern-matching/ObjectMatcher.spec.ts.html#lineNumber7",
    "ObjectMatcher when working with Tiny Types",
    "test"
  ],
  [
    "",
    "test-file/spec/pattern-matching/ObjectMatcher.spec.ts.html#lineNumber40",
    "ObjectMatcher when working with Tiny Types matches identical objects",
    "test"
  ],
  [
    "",
    "test-file/spec/pattern-matching/ObjectMatcher.spec.ts.html#lineNumber56",
    "ObjectMatcher when working with regular classes",
    "test"
  ],
  [
    "",
    "test-file/spec/pattern-matching/StringMatcher.spec.ts.html#lineNumber5",
    "StringMatcher",
    "test"
  ],
  [
    "tinytype src/tinytype.ts~tinytype,tinytype",
    "test-file/spec/TinyType.spec.ts.html#lineNumber6",
    "TinyType",
    "test"
  ],
  [
    "tinytype#equals src/tinytype.ts~tinytype#equals,tinytype#equals",
    "test-file/spec/TinyType.spec.ts.html#lineNumber123",
    "TinyType ::equals",
    "test"
  ],
  [
    "",
    "test-file/spec/TinyType.spec.ts.html#lineNumber176",
    "TinyType ::equals is recursive",
    "test"
  ],
  [
    "",
    "test-file/spec/TinyType.spec.ts.html#lineNumber161",
    "TinyType ::equals is reflexive",
    "test"
  ],
  [
    "",
    "test-file/spec/TinyType.spec.ts.html#lineNumber165",
    "TinyType ::equals is symmetric",
    "test"
  ],
  [
    "",
    "test-file/spec/TinyType.spec.ts.html#lineNumber170",
    "TinyType ::equals is transitive",
    "test"
  ],
  [
    "",
    "test-file/spec/TinyType.spec.ts.html#lineNumber181",
    "TinyType ::equals works for private fields",
    "test"
  ],
  [
    "tinytype#tostring src/tinytype.ts~tinytype#tostring,tinytype#tostring",
    "test-file/spec/TinyType.spec.ts.html#lineNumber205",
    "TinyType ::toString",
    "test"
  ],
  [
    "",
    "test-file/spec/TinyType.spec.ts.html#lineNumber257",
    "TinyType ::toString mentions the class and its fields, but not the methods",
    "test"
  ],
  [
    "",
    "test-file/spec/TinyType.spec.ts.html#lineNumber253",
    "TinyType ::toString mentions the class and its properties",
    "test"
  ],
  [
    "",
    "test-file/spec/TinyType.spec.ts.html#lineNumber281",
    "TinyType ::toString only cares about the fields, not the methods",
    "test"
  ],
  [
    "tinytype src/tinytype.ts~tinytype,tinytype",
    "test-file/spec/TinyType.spec.ts.html#lineNumber355",
    "TinyType de-serialisation",
    "test"
  ],
  [
    "",
    "test-file/spec/TinyType.spec.ts.html#lineNumber466",
    "TinyType de-serialisation custom fromJSON can de-serialise a serialised single-value TinyType",
    "test"
  ],
  [
    "",
    "test-file/spec/TinyType.spec.ts.html#lineNumber471",
    "TinyType de-serialisation custom fromJSON can recursively de-serialise a serialised complex TinyType",
    "test"
  ],
  [
    "",
    "test-file/spec/TinyType.spec.ts.html#lineNumber7",
    "TinyType definition",
    "test"
  ],
  [
    "tinytypeof src/tinytype.ts~tinytypeof,tinytypeof",
    "test-file/spec/TinyType.spec.ts.html#lineNumber9",
    "TinyType definition can be a one-liner for TinyTypes representing a single value",
    "test"
  ],
  [
    "tinytype tinytypeof src/tinytype.ts~tinytype,tinytype src/tinytype.ts~tinytypeof,tinytypeof",
    "test-file/spec/TinyType.spec.ts.html#lineNumber71",
    "TinyType definition can be mixed and matched",
    "test"
  ],
  [
    "tinytype tinytypeof src/tinytype.ts~tinytype,tinytype src/tinytype.ts~tinytypeof,tinytypeof",
    "test-file/spec/TinyType.spec.ts.html#lineNumber29",
    "TinyType definition needs to extend the TinyType for types with more than one value",
    "test"
  ],
  [
    "tinytype#tojson src/tinytype.ts~tinytype#tojson,tinytype#tojson",
    "test-file/spec/TinyType.spec.ts.html#lineNumber288",
    "TinyType serialisation",
    "test"
  ],
  [
    "",
    "test-file/spec/TinyType.spec.ts.html#lineNumber327",
    "TinyType serialisation ::toJSON",
    "test"
  ],
  [
    "",
    "test-file/spec/TinyType.spec.ts.html#lineNumber340",
    "TinyType serialisation ::toJSON ",
    "test"
  ],
  [
    "",
    "test-file/spec/TinyType.spec.ts.html#lineNumber332",
    "TinyType serialisation ::toJSON should serialise a complex TinyType recursively",
    "test"
  ],
  [
    "spec/tinytype.spec.ts",
    "test-file/spec/TinyType.spec.ts.html",
    "spec/TinyType.spec.ts",
    "testFile"
  ],
  [
    "spec/json.spec.ts",
    "test-file/spec/json.spec.ts.html",
    "spec/json.spec.ts",
    "testFile"
  ],
  [
    "spec/match.spec.ts",
    "test-file/spec/match.spec.ts.html",
    "spec/match.spec.ts",
    "testFile"
  ],
  [
    "spec/pattern-matching/identitymatcher.spec.ts",
    "test-file/spec/pattern-matching/IdentityMatcher.spec.ts.html",
    "spec/pattern-matching/IdentityMatcher.spec.ts",
    "testFile"
  ],
  [
    "spec/pattern-matching/objectmatcher.spec.ts",
    "test-file/spec/pattern-matching/ObjectMatcher.spec.ts.html",
    "spec/pattern-matching/ObjectMatcher.spec.ts",
    "testFile"
  ],
  [
    "spec/pattern-matching/stringmatcher.spec.ts",
    "test-file/spec/pattern-matching/StringMatcher.spec.ts.html",
    "spec/pattern-matching/StringMatcher.spec.ts",
    "testFile"
  ],
  [
    "spec/pattern-matching/rules/matchesanything.spec.ts",
    "test-file/spec/pattern-matching/rules/MatchesAnything.spec.ts.html",
    "spec/pattern-matching/rules/MatchesAnything.spec.ts",
    "testFile"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/tinytype.ts",
    "file/src/TinyType.ts.html",
    "src/TinyType.ts",
    "file"
  ],
  [
    "src/tinytype.ts~tinytype#equals",
    "class/src/TinyType.ts~TinyType.html#instance-method-equals",
    "src/TinyType.ts~TinyType#equals",
    "method"
  ],
  [
    "src/tinytype.ts~tinytype#tojson",
    "class/src/TinyType.ts~TinyType.html#instance-method-toJSON",
    "src/TinyType.ts~TinyType#toJSON",
    "method"
  ],
  [
    "src/tinytype.ts~tinytype#tostring",
    "class/src/TinyType.ts~TinyType.html#instance-method-toString",
    "src/TinyType.ts~TinyType#toString",
    "method"
  ],
  [
    "src/index.ts",
    "file/src/index.ts.html",
    "src/index.ts",
    "file"
  ],
  [
    "src/match.ts",
    "file/src/match.ts.html",
    "src/match.ts",
    "file"
  ],
  [
    "src/pattern-matching/identitymatcher.ts",
    "file/src/pattern-matching/IdentityMatcher.ts.html",
    "src/pattern-matching/IdentityMatcher.ts",
    "file"
  ],
  [
    "src/pattern-matching/identitymatcher.ts~identitymatcher#when",
    "class/src/pattern-matching/IdentityMatcher.ts~IdentityMatcher.html#instance-method-when",
    "src/pattern-matching/IdentityMatcher.ts~IdentityMatcher#when",
    "method"
  ],
  [
    "src/pattern-matching/objectmatcher.ts",
    "file/src/pattern-matching/ObjectMatcher.ts.html",
    "src/pattern-matching/ObjectMatcher.ts",
    "file"
  ],
  [
    "src/pattern-matching/objectmatcher.ts~objectmatcher#rule",
    "class/src/pattern-matching/ObjectMatcher.ts~ObjectMatcher.html#instance-method-rule",
    "src/pattern-matching/ObjectMatcher.ts~ObjectMatcher#rule",
    "method"
  ],
  [
    "src/pattern-matching/objectmatcher.ts~objectmatcher#when",
    "class/src/pattern-matching/ObjectMatcher.ts~ObjectMatcher.html#instance-method-when",
    "src/pattern-matching/ObjectMatcher.ts~ObjectMatcher#when",
    "method"
  ],
  [
    "src/pattern-matching/patternmatcher.ts",
    "file/src/pattern-matching/PatternMatcher.ts.html",
    "src/pattern-matching/PatternMatcher.ts",
    "file"
  ],
  [
    "src/pattern-matching/patternmatcher.ts~patternmatcher#constructor",
    "class/src/pattern-matching/PatternMatcher.ts~PatternMatcher.html#instance-constructor-constructor",
    "src/pattern-matching/PatternMatcher.ts~PatternMatcher#constructor",
    "method"
  ],
  [
    "src/pattern-matching/patternmatcher.ts~patternmatcher#else",
    "class/src/pattern-matching/PatternMatcher.ts~PatternMatcher.html#instance-method-else",
    "src/pattern-matching/PatternMatcher.ts~PatternMatcher#else",
    "method"
  ],
  [
    "src/pattern-matching/patternmatcher.ts~patternmatcher#rules",
    "class/src/pattern-matching/PatternMatcher.ts~PatternMatcher.html#instance-member-rules",
    "src/pattern-matching/PatternMatcher.ts~PatternMatcher#rules",
    "member"
  ],
  [
    "src/pattern-matching/patternmatcher.ts~patternmatcher#value",
    "class/src/pattern-matching/PatternMatcher.ts~PatternMatcher.html#instance-member-value",
    "src/pattern-matching/PatternMatcher.ts~PatternMatcher#value",
    "member"
  ],
  [
    "src/pattern-matching/stringmatcher.ts",
    "file/src/pattern-matching/StringMatcher.ts.html",
    "src/pattern-matching/StringMatcher.ts",
    "file"
  ],
  [
    "src/pattern-matching/stringmatcher.ts~stringmatcher#when",
    "class/src/pattern-matching/StringMatcher.ts~StringMatcher.html#instance-method-when",
    "src/pattern-matching/StringMatcher.ts~StringMatcher#when",
    "method"
  ],
  [
    "src/pattern-matching/index.ts",
    "file/src/pattern-matching/index.ts.html",
    "src/pattern-matching/index.ts",
    "file"
  ],
  [
    "src/pattern-matching/rules/matcherrule.ts",
    "file/src/pattern-matching/rules/MatcherRule.ts.html",
    "src/pattern-matching/rules/MatcherRule.ts",
    "file"
  ],
  [
    "src/pattern-matching/rules/matcherrule.ts~matcherrule#constructor",
    "class/src/pattern-matching/rules/MatcherRule.ts~MatcherRule.html#instance-constructor-constructor",
    "src/pattern-matching/rules/MatcherRule.ts~MatcherRule#constructor",
    "method"
  ],
  [
    "src/pattern-matching/rules/matcherrule.ts~matcherrule#execute",
    "class/src/pattern-matching/rules/MatcherRule.ts~MatcherRule.html#instance-method-execute",
    "src/pattern-matching/rules/MatcherRule.ts~MatcherRule#execute",
    "method"
  ],
  [
    "src/pattern-matching/rules/matcherrule.ts~matcherrule#transformation",
    "class/src/pattern-matching/rules/MatcherRule.ts~MatcherRule.html#instance-member-transformation",
    "src/pattern-matching/rules/MatcherRule.ts~MatcherRule#transformation",
    "member"
  ],
  [
    "src/pattern-matching/rules/matchesanything.ts",
    "file/src/pattern-matching/rules/MatchesAnything.ts.html",
    "src/pattern-matching/rules/MatchesAnything.ts",
    "file"
  ],
  [
    "src/pattern-matching/rules/matchesanything.ts~matchesanything#constructor",
    "class/src/pattern-matching/rules/MatchesAnything.ts~MatchesAnything.html#instance-constructor-constructor",
    "src/pattern-matching/rules/MatchesAnything.ts~MatchesAnything#constructor",
    "method"
  ],
  [
    "src/pattern-matching/rules/matchesanything.ts~matchesanything#matches",
    "class/src/pattern-matching/rules/MatchesAnything.ts~MatchesAnything.html#instance-method-matches",
    "src/pattern-matching/rules/MatchesAnything.ts~MatchesAnything#matches",
    "method"
  ],
  [
    "src/pattern-matching/rules/matchesequaltinytype.ts",
    "file/src/pattern-matching/rules/MatchesEqualTinyType.ts.html",
    "src/pattern-matching/rules/MatchesEqualTinyType.ts",
    "file"
  ],
  [
    "src/pattern-matching/rules/matchesequaltinytype.ts~matchesequaltinytype#constructor",
    "class/src/pattern-matching/rules/MatchesEqualTinyType.ts~MatchesEqualTinyType.html#instance-constructor-constructor",
    "src/pattern-matching/rules/MatchesEqualTinyType.ts~MatchesEqualTinyType#constructor",
    "method"
  ],
  [
    "src/pattern-matching/rules/matchesequaltinytype.ts~matchesequaltinytype#matches",
    "class/src/pattern-matching/rules/MatchesEqualTinyType.ts~MatchesEqualTinyType.html#instance-method-matches",
    "src/pattern-matching/rules/MatchesEqualTinyType.ts~MatchesEqualTinyType#matches",
    "method"
  ],
  [
    "src/pattern-matching/rules/matchesequaltinytype.ts~matchesequaltinytype#pattern",
    "class/src/pattern-matching/rules/MatchesEqualTinyType.ts~MatchesEqualTinyType.html#instance-member-pattern",
    "src/pattern-matching/rules/MatchesEqualTinyType.ts~MatchesEqualTinyType#pattern",
    "member"
  ],
  [
    "src/pattern-matching/rules/matchesidentical.ts",
    "file/src/pattern-matching/rules/MatchesIdentical.ts.html",
    "src/pattern-matching/rules/MatchesIdentical.ts",
    "file"
  ],
  [
    "src/pattern-matching/rules/matchesidentical.ts~matchesidentical#constructor",
    "class/src/pattern-matching/rules/MatchesIdentical.ts~MatchesIdentical.html#instance-constructor-constructor",
    "src/pattern-matching/rules/MatchesIdentical.ts~MatchesIdentical#constructor",
    "method"
  ],
  [
    "src/pattern-matching/rules/matchesidentical.ts~matchesidentical#matches",
    "class/src/pattern-matching/rules/MatchesIdentical.ts~MatchesIdentical.html#instance-method-matches",
    "src/pattern-matching/rules/MatchesIdentical.ts~MatchesIdentical#matches",
    "method"
  ],
  [
    "src/pattern-matching/rules/matchesidentical.ts~matchesidentical#pattern",
    "class/src/pattern-matching/rules/MatchesIdentical.ts~MatchesIdentical.html#instance-member-pattern",
    "src/pattern-matching/rules/MatchesIdentical.ts~MatchesIdentical#pattern",
    "member"
  ],
  [
    "src/pattern-matching/rules/matchesobjectswithcommonprototype.ts",
    "file/src/pattern-matching/rules/MatchesObjectsWithCommonPrototype.ts.html",
    "src/pattern-matching/rules/MatchesObjectsWithCommonPrototype.ts",
    "file"
  ],
  [
    "src/pattern-matching/rules/matchesobjectswithcommonprototype.ts~matchesobjectswithcommonprototype#constructor",
    "class/src/pattern-matching/rules/MatchesObjectsWithCommonPrototype.ts~MatchesObjectsWithCommonPrototype.html#instance-constructor-constructor",
    "src/pattern-matching/rules/MatchesObjectsWithCommonPrototype.ts~MatchesObjectsWithCommonPrototype#constructor",
    "method"
  ],
  [
    "src/pattern-matching/rules/matchesobjectswithcommonprototype.ts~matchesobjectswithcommonprototype#matches",
    "class/src/pattern-matching/rules/MatchesObjectsWithCommonPrototype.ts~MatchesObjectsWithCommonPrototype.html#instance-method-matches",
    "src/pattern-matching/rules/MatchesObjectsWithCommonPrototype.ts~MatchesObjectsWithCommonPrototype#matches",
    "method"
  ],
  [
    "src/pattern-matching/rules/matchesobjectswithcommonprototype.ts~matchesobjectswithcommonprototype#pattern",
    "class/src/pattern-matching/rules/MatchesObjectsWithCommonPrototype.ts~MatchesObjectsWithCommonPrototype.html#instance-member-pattern",
    "src/pattern-matching/rules/MatchesObjectsWithCommonPrototype.ts~MatchesObjectsWithCommonPrototype#pattern",
    "member"
  ],
  [
    "src/pattern-matching/rules/matchesregexp.ts",
    "file/src/pattern-matching/rules/MatchesRegExp.ts.html",
    "src/pattern-matching/rules/MatchesRegExp.ts",
    "file"
  ],
  [
    "src/pattern-matching/rules/matchesregexp.ts~matchesregexp#constructor",
    "class/src/pattern-matching/rules/MatchesRegExp.ts~MatchesRegExp.html#instance-constructor-constructor",
    "src/pattern-matching/rules/MatchesRegExp.ts~MatchesRegExp#constructor",
    "method"
  ],
  [
    "src/pattern-matching/rules/matchesregexp.ts~matchesregexp#matches",
    "class/src/pattern-matching/rules/MatchesRegExp.ts~MatchesRegExp.html#instance-method-matches",
    "src/pattern-matching/rules/MatchesRegExp.ts~MatchesRegExp#matches",
    "method"
  ],
  [
    "src/pattern-matching/rules/matchesregexp.ts~matchesregexp#pattern",
    "class/src/pattern-matching/rules/MatchesRegExp.ts~MatchesRegExp.html#instance-member-pattern",
    "src/pattern-matching/rules/MatchesRegExp.ts~MatchesRegExp#pattern",
    "member"
  ],
  [
    "src/pattern-matching/rules/index.ts",
    "file/src/pattern-matching/rules/index.ts.html",
    "src/pattern-matching/rules/index.ts",
    "file"
  ],
  [
    "src/types.ts",
    "file/src/types.ts.html",
    "src/types.ts",
    "file"
  ]
]