window.esdocSearchIndex = [
  [
    "match src/match.ts~match,match",
    "test-file/spec/match.spec.ts.html#lineNumber7",
    "",
    "test"
  ],
  [
    "match src/match.ts~match,match",
    "test-file/spec/match.spec.ts.html#lineNumber9",
    " default rules",
    "test"
  ],
  [
    "",
    "test-file/spec/match.spec.ts.html#lineNumber17",
    " default rules ",
    "test"
  ],
  [
    "",
    "test-file/spec/match.spec.ts.html#lineNumber10",
    " default rules ",
    "test"
  ],
  [
    "",
    "test-file/spec/match.spec.ts.html#lineNumber25",
    " when selecting a matcher",
    "test"
  ],
  [
    "match tinytype tinytypeof src/match.ts~match,match src/tinytype.ts~tinytype,tinytype src/tinytype.ts~tinytypeof,tinytypeof",
    "test-file/spec/match.spec.ts.html#lineNumber75",
    " when working with TinyTypes",
    "test"
  ],
  [
    "check src/check.ts~check,check",
    "test-file/spec/chec.spec.ts.html#lineNumber5",
    "::check",
    "test"
  ],
  [
    "",
    "test-file/spec/chec.spec.ts.html#lineNumber6",
    "::check ",
    "test"
  ],
  [
    "tiny-types/lib/predicates/predicate~failure",
    "class/src/predicates/Predicate.ts~Failure.html",
    "<span>Failure</span> <span class=\"search-result-import-path\">tiny-types/lib/predicates/Predicate</span>",
    "class"
  ],
  [
    "tiny-types/lib/predicates/predicate~predicate",
    "class/src/predicates/Predicate.ts~Predicate.html",
    "<span>Predicate</span> <span class=\"search-result-import-path\">tiny-types/lib/predicates/Predicate</span>",
    "class"
  ],
  [
    "tiny-types/lib/predicates/predicate~result",
    "class/src/predicates/Predicate.ts~Result.html",
    "<span>Result</span> <span class=\"search-result-import-path\">tiny-types/lib/predicates/Predicate</span>",
    "class"
  ],
  [
    "tiny-types/lib/predicates/predicate~success",
    "class/src/predicates/Predicate.ts~Success.html",
    "<span>Success</span> <span class=\"search-result-import-path\">tiny-types/lib/predicates/Predicate</span>",
    "class"
  ],
  [
    "tiny-types/lib/tinytype~tinytype",
    "class/src/TinyType.ts~TinyType.html",
    "<span>TinyType</span> <span class=\"search-result-import-path\">tiny-types/lib/TinyType</span>",
    "class"
  ],
  [
    "tiny-types/lib/tinytype~tinytypeof",
    "function/index.html#static-function-TinyTypeOf",
    "<span>TinyTypeOf</span> <span class=\"search-result-import-path\">tiny-types/lib/TinyType</span>",
    "function"
  ],
  [
    "tiny-types/lib/predicates/and~and",
    "function/index.html#static-function-and",
    "<span>and</span> <span class=\"search-result-import-path\">tiny-types/lib/predicates/and</span>",
    "function"
  ],
  [
    "tiny-types/lib/check~check",
    "function/index.html#static-function-check",
    "<span>check</span> <span class=\"search-result-import-path\">tiny-types/lib/check</span>",
    "function"
  ],
  [
    "tiny-types/lib/predicates/haslengthof~haslengthof",
    "function/index.html#static-function-hasLengthOf",
    "<span>hasLengthOf</span> <span class=\"search-result-import-path\">tiny-types/lib/predicates/hasLengthOf</span>",
    "function"
  ],
  [
    "tiny-types/lib/predicates/isarray~isarray",
    "function/index.html#static-function-isArray",
    "<span>isArray</span> <span class=\"search-result-import-path\">tiny-types/lib/predicates/isArray</span>",
    "function"
  ],
  [
    "tiny-types/lib/predicates/isdefined~isdefined",
    "function/index.html#static-function-isDefined",
    "<span>isDefined</span> <span class=\"search-result-import-path\">tiny-types/lib/predicates/isDefined</span>",
    "function"
  ],
  [
    "tiny-types/lib/predicates/isequalto~isequalto",
    "function/index.html#static-function-isEqualTo",
    "<span>isEqualTo</span> <span class=\"search-result-import-path\">tiny-types/lib/predicates/isEqualTo</span>",
    "function"
  ],
  [
    "tiny-types/lib/predicates/isgreaterthan~isgreaterthan",
    "function/index.html#static-function-isGreaterThan",
    "<span>isGreaterThan</span> <span class=\"search-result-import-path\">tiny-types/lib/predicates/isGreaterThan</span>",
    "function"
  ],
  [
    "tiny-types/lib/predicates/isgreaterthanorequalto~isgreaterthanorequalto",
    "function/index.html#static-function-isGreaterThanOrEqualTo",
    "<span>isGreaterThanOrEqualTo</span> <span class=\"search-result-import-path\">tiny-types/lib/predicates/isGreaterThanOrEqualTo</span>",
    "function"
  ],
  [
    "tiny-types/lib/predicates/isinrange~isinrange",
    "function/index.html#static-function-isInRange",
    "<span>isInRange</span> <span class=\"search-result-import-path\">tiny-types/lib/predicates/isInRange</span>",
    "function"
  ],
  [
    "tiny-types/lib/predicates/isinteger~isinteger",
    "function/index.html#static-function-isInteger",
    "<span>isInteger</span> <span class=\"search-result-import-path\">tiny-types/lib/predicates/isInteger</span>",
    "function"
  ],
  [
    "tiny-types/lib/predicates/islessthan~islessthan",
    "function/index.html#static-function-isLessThan",
    "<span>isLessThan</span> <span class=\"search-result-import-path\">tiny-types/lib/predicates/isLessThan</span>",
    "function"
  ],
  [
    "tiny-types/lib/predicates/islessthanorequalto~islessthanorequalto",
    "function/index.html#static-function-isLessThanOrEqualTo",
    "<span>isLessThanOrEqualTo</span> <span class=\"search-result-import-path\">tiny-types/lib/predicates/isLessThanOrEqualTo</span>",
    "function"
  ],
  [
    "tiny-types/lib/match~match",
    "function/index.html#static-function-match",
    "<span>match</span> <span class=\"search-result-import-path\">tiny-types/lib/match</span>",
    "function"
  ],
  [
    "tiny-types/lib/predicates/or~or",
    "function/index.html#static-function-or",
    "<span>or</span> <span class=\"search-result-import-path\">tiny-types/lib/predicates/or</span>",
    "function"
  ],
  [
    "",
    "test-file/spec/json.spec.ts.html#lineNumber2",
    "JSON",
    "test"
  ],
  [
    "jsonarray jsonarray,jsonarray",
    "test-file/spec/json.spec.ts.html#lineNumber5",
    "JSON JSONArray",
    "test"
  ],
  [
    "",
    "test-file/spec/json.spec.ts.html#lineNumber6",
    "JSON JSONArray ",
    "test"
  ],
  [
    "jsonobject jsonobject,jsonobject",
    "test-file/spec/json.spec.ts.html#lineNumber11",
    "JSON JSONObject",
    "test"
  ],
  [
    "",
    "test-file/spec/json.spec.ts.html#lineNumber12",
    "JSON JSONObject ",
    "test"
  ],
  [
    "jsonprimitive jsonprimitive,jsonprimitive",
    "test-file/spec/json.spec.ts.html#lineNumber23",
    "JSON JSONPrimitive",
    "test"
  ],
  [
    "",
    "test-file/spec/json.spec.ts.html#lineNumber24",
    "JSON JSONPrimitive ",
    "test"
  ],
  [
    "jsonvalue jsonvalue,jsonvalue",
    "test-file/spec/json.spec.ts.html#lineNumber29",
    "JSON JSONValue",
    "test"
  ],
  [
    "",
    "test-file/spec/json.spec.ts.html#lineNumber30",
    "JSON JSONValue describes any value that can be represented as JSON",
    "test"
  ],
  [
    "tinytype src/tinytype.ts~tinytype,tinytype",
    "test-file/spec/TinyType.spec.ts.html#lineNumber6",
    "TinyType",
    "test"
  ],
  [
    "tinytype#equals src/tinytype.ts~tinytype#equals,tinytype#equals",
    "test-file/spec/TinyType.spec.ts.html#lineNumber124",
    "TinyType ::equals",
    "test"
  ],
  [
    "",
    "test-file/spec/TinyType.spec.ts.html#lineNumber177",
    "TinyType ::equals is recursive",
    "test"
  ],
  [
    "",
    "test-file/spec/TinyType.spec.ts.html#lineNumber162",
    "TinyType ::equals is reflexive",
    "test"
  ],
  [
    "",
    "test-file/spec/TinyType.spec.ts.html#lineNumber166",
    "TinyType ::equals is symmetric",
    "test"
  ],
  [
    "",
    "test-file/spec/TinyType.spec.ts.html#lineNumber171",
    "TinyType ::equals is transitive",
    "test"
  ],
  [
    "",
    "test-file/spec/TinyType.spec.ts.html#lineNumber182",
    "TinyType ::equals works for private fields",
    "test"
  ],
  [
    "tinytype#tostring src/tinytype.ts~tinytype#tostring,tinytype#tostring",
    "test-file/spec/TinyType.spec.ts.html#lineNumber206",
    "TinyType ::toString",
    "test"
  ],
  [
    "",
    "test-file/spec/TinyType.spec.ts.html#lineNumber258",
    "TinyType ::toString mentions the class and its fields, but not the methods",
    "test"
  ],
  [
    "",
    "test-file/spec/TinyType.spec.ts.html#lineNumber254",
    "TinyType ::toString mentions the class and its properties",
    "test"
  ],
  [
    "",
    "test-file/spec/TinyType.spec.ts.html#lineNumber282",
    "TinyType ::toString only cares about the fields, not the methods",
    "test"
  ],
  [
    "tinytype src/tinytype.ts~tinytype,tinytype",
    "test-file/spec/TinyType.spec.ts.html#lineNumber356",
    "TinyType de-serialisation",
    "test"
  ],
  [
    "",
    "test-file/spec/TinyType.spec.ts.html#lineNumber467",
    "TinyType de-serialisation custom fromJSON can de-serialise a serialised single-value TinyType",
    "test"
  ],
  [
    "",
    "test-file/spec/TinyType.spec.ts.html#lineNumber472",
    "TinyType de-serialisation custom fromJSON can recursively de-serialise a serialised complex TinyType",
    "test"
  ],
  [
    "tinytype src/tinytype.ts~tinytype,tinytype",
    "test-file/spec/TinyType.spec.ts.html#lineNumber8",
    "TinyType definition",
    "test"
  ],
  [
    "tinytypeof src/tinytype.ts~tinytypeof,tinytypeof",
    "test-file/spec/TinyType.spec.ts.html#lineNumber10",
    "TinyType definition can be a one-liner for TinyTypes representing a single value",
    "test"
  ],
  [
    "tinytype tinytypeof src/tinytype.ts~tinytype,tinytype src/tinytype.ts~tinytypeof,tinytypeof",
    "test-file/spec/TinyType.spec.ts.html#lineNumber72",
    "TinyType definition can be mixed and matched",
    "test"
  ],
  [
    "tinytype tinytypeof src/tinytype.ts~tinytype,tinytype src/tinytype.ts~tinytypeof,tinytypeof",
    "test-file/spec/TinyType.spec.ts.html#lineNumber30",
    "TinyType definition needs to extend the TinyType for types with more than one value",
    "test"
  ],
  [
    "tinytype#tojson src/tinytype.ts~tinytype#tojson,tinytype#tojson",
    "test-file/spec/TinyType.spec.ts.html#lineNumber289",
    "TinyType serialisation",
    "test"
  ],
  [
    "",
    "test-file/spec/TinyType.spec.ts.html#lineNumber328",
    "TinyType serialisation ::toJSON",
    "test"
  ],
  [
    "",
    "test-file/spec/TinyType.spec.ts.html#lineNumber341",
    "TinyType serialisation ::toJSON ",
    "test"
  ],
  [
    "",
    "test-file/spec/TinyType.spec.ts.html#lineNumber333",
    "TinyType serialisation ::toJSON should serialise a complex TinyType recursively",
    "test"
  ],
  [
    "",
    "test-file/spec/pattern-matching/ObjectMatcher.spec.ts.html#lineNumber6",
    "pattern-matching",
    "test"
  ],
  [
    "",
    "test-file/spec/pattern-matching/IdentityMatcher.spec.ts.html#lineNumber5",
    "pattern-matching",
    "test"
  ],
  [
    "",
    "test-file/spec/pattern-matching/StringMatcher.spec.ts.html#lineNumber5",
    "pattern-matching",
    "test"
  ],
  [
    "",
    "test-file/spec/pattern-matching/rules/MatchesAnything.spec.ts.html#lineNumber5",
    "pattern-matching",
    "test"
  ],
  [
    "",
    "test-file/spec/pattern-matching/IdentityMatcher.spec.ts.html#lineNumber6",
    "pattern-matching IdentityMatcher",
    "test"
  ],
  [
    "",
    "test-file/spec/pattern-matching/IdentityMatcher.spec.ts.html#lineNumber23",
    "pattern-matching IdentityMatcher matches a symbol",
    "test"
  ],
  [
    "",
    "test-file/spec/pattern-matching/ObjectMatcher.spec.ts.html#lineNumber7",
    "pattern-matching ObjectMatcher",
    "test"
  ],
  [
    "",
    "test-file/spec/pattern-matching/ObjectMatcher.spec.ts.html#lineNumber8",
    "pattern-matching ObjectMatcher when working with Tiny Types",
    "test"
  ],
  [
    "",
    "test-file/spec/pattern-matching/ObjectMatcher.spec.ts.html#lineNumber40",
    "pattern-matching ObjectMatcher when working with Tiny Types matches identical objects",
    "test"
  ],
  [
    "",
    "test-file/spec/pattern-matching/ObjectMatcher.spec.ts.html#lineNumber55",
    "pattern-matching ObjectMatcher when working with regular classes",
    "test"
  ],
  [
    "",
    "test-file/spec/pattern-matching/StringMatcher.spec.ts.html#lineNumber6",
    "pattern-matching StringMatcher",
    "test"
  ],
  [
    "",
    "test-file/spec/pattern-matching/rules/MatchesAnything.spec.ts.html#lineNumber6",
    "pattern-matching rules",
    "test"
  ],
  [
    "",
    "test-file/spec/pattern-matching/rules/MatchesAnything.spec.ts.html#lineNumber7",
    "pattern-matching rules MatchesAnything",
    "test"
  ],
  [
    "",
    "test-file/spec/predicates/isInteger.spec.ts.html#lineNumber5",
    "predicates",
    "test"
  ],
  [
    "",
    "test-file/spec/predicates/isLessThan.spec.ts.html#lineNumber5",
    "predicates",
    "test"
  ],
  [
    "",
    "test-file/spec/predicates/isInRange.spec.ts.html#lineNumber6",
    "predicates",
    "test"
  ],
  [
    "",
    "test-file/spec/predicates/isGreaterThanOrEqualTo.spec.ts.html#lineNumber5",
    "predicates",
    "test"
  ],
  [
    "",
    "test-file/spec/predicates/isLessThanOrEqual.spec.ts.html#lineNumber5",
    "predicates",
    "test"
  ],
  [
    "",
    "test-file/spec/predicates/or.spec.ts.html#lineNumber5",
    "predicates",
    "test"
  ],
  [
    "",
    "test-file/spec/predicates/and.spec.ts.html#lineNumber5",
    "predicates",
    "test"
  ],
  [
    "",
    "test-file/spec/predicates/isGreaterThan.spec.ts.html#lineNumber5",
    "predicates",
    "test"
  ],
  [
    "",
    "test-file/spec/predicates/hasLengthOf.spec.ts.html#lineNumber5",
    "predicates",
    "test"
  ],
  [
    "",
    "test-file/spec/predicates/isEqualTo.spec.ts.html#lineNumber5",
    "predicates",
    "test"
  ],
  [
    "",
    "test-file/spec/predicates/isDefined.spec.ts.html#lineNumber5",
    "predicates",
    "test"
  ],
  [
    "",
    "test-file/spec/predicates/isArray.spec.ts.html#lineNumber5",
    "predicates",
    "test"
  ],
  [
    "and src/predicates/and.ts~and,and",
    "test-file/spec/predicates/and.spec.ts.html#lineNumber7",
    "predicates ::and",
    "test"
  ],
  [
    "",
    "test-file/spec/predicates/and.spec.ts.html#lineNumber29",
    "predicates ::and complains if there are no predicates specified",
    "test"
  ],
  [
    "",
    "test-file/spec/predicates/and.spec.ts.html#lineNumber21",
    "predicates ::and ensures that all the predicates are met",
    "test"
  ],
  [
    "haslengthof src/predicates/haslengthof.ts~haslengthof,haslengthof",
    "test-file/spec/predicates/hasLengthOf.spec.ts.html#lineNumber7",
    "predicates ::hasLengthOf",
    "test"
  ],
  [
    "haslengthof src/predicates/haslengthof.ts~haslengthof,haslengthof",
    "test-file/spec/predicates/hasLengthOf.spec.ts.html#lineNumber36",
    "predicates ::hasLengthOf when used with arrays",
    "test"
  ],
  [
    "",
    "test-file/spec/predicates/hasLengthOf.spec.ts.html#lineNumber50",
    "predicates ::hasLengthOf when used with arrays ensures that the value has a correct length",
    "test"
  ],
  [
    "haslengthof src/predicates/haslengthof.ts~haslengthof,haslengthof",
    "test-file/spec/predicates/hasLengthOf.spec.ts.html#lineNumber9",
    "predicates ::hasLengthOf when used with strings",
    "test"
  ],
  [
    "",
    "test-file/spec/predicates/hasLengthOf.spec.ts.html#lineNumber23",
    "predicates ::hasLengthOf when used with strings ensures that the value has a correct length",
    "test"
  ],
  [
    "isarray src/predicates/isarray.ts~isarray,isarray",
    "test-file/spec/predicates/isArray.spec.ts.html#lineNumber7",
    "predicates ::isArray",
    "test"
  ],
  [
    "",
    "test-file/spec/predicates/isArray.spec.ts.html#lineNumber21",
    "predicates ::isArray ensures that the argument is an array",
    "test"
  ],
  [
    "isdefined src/predicates/isdefined.ts~isdefined,isdefined",
    "test-file/spec/predicates/isDefined.spec.ts.html#lineNumber7",
    "predicates ::isDefined",
    "test"
  ],
  [
    "",
    "test-file/spec/predicates/isDefined.spec.ts.html#lineNumber21",
    "predicates ::isDefined ensures that the value is defined",
    "test"
  ],
  [
    "isequalto src/predicates/isequalto.ts~isequalto,isequalto",
    "test-file/spec/predicates/isEqualTo.spec.ts.html#lineNumber7",
    "predicates ::isEqualTo",
    "test"
  ],
  [
    "isequalto src/predicates/isequalto.ts~isequalto,isequalto",
    "test-file/spec/predicates/isEqualTo.spec.ts.html#lineNumber9",
    "predicates ::isEqualTo when working with Tiny Types",
    "test"
  ],
  [
    "",
    "test-file/spec/predicates/isEqualTo.spec.ts.html#lineNumber62",
    "predicates ::isEqualTo when working with Tiny Types complains if the objects are not identical by value",
    "test"
  ],
  [
    "",
    "test-file/spec/predicates/isEqualTo.spec.ts.html#lineNumber56",
    "predicates ::isEqualTo when working with Tiny Types ensures that objects are identical by value",
    "test"
  ],
  [
    "isequalto src/predicates/isequalto.ts~isequalto,isequalto",
    "test-file/spec/predicates/isEqualTo.spec.ts.html#lineNumber72",
    "predicates ::isEqualTo when working with primitive types",
    "test"
  ],
  [
    "isgreaterthan src/predicates/isgreaterthan.ts~isgreaterthan,isgreaterthan",
    "test-file/spec/predicates/isGreaterThan.spec.ts.html#lineNumber7",
    "predicates ::isGreaterThan",
    "test"
  ],
  [
    "",
    "test-file/spec/predicates/isGreaterThan.spec.ts.html#lineNumber24",
    "predicates ::isGreaterThan complains if the argument is more than a specified number",
    "test"
  ],
  [
    "",
    "test-file/spec/predicates/isGreaterThan.spec.ts.html#lineNumber21",
    "predicates ::isGreaterThan ensures that the argument is greater than a specified number",
    "test"
  ],
  [
    "isgreaterthanorequalto src/predicates/isgreaterthanorequalto.ts~isgreaterthanorequalto,isgreaterthanorequalto",
    "test-file/spec/predicates/isGreaterThanOrEqualTo.spec.ts.html#lineNumber7",
    "predicates ::isGreaterThanOrEqualTo",
    "test"
  ],
  [
    "",
    "test-file/spec/predicates/isGreaterThanOrEqualTo.spec.ts.html#lineNumber25",
    "predicates ::isGreaterThanOrEqualTo complains if the argument is less than the lower bound",
    "test"
  ],
  [
    "isinrange src/predicates/isinrange.ts~isinrange,isinrange",
    "test-file/spec/predicates/isInRange.spec.ts.html#lineNumber8",
    "predicates ::isInRange",
    "test"
  ],
  [
    "",
    "test-file/spec/predicates/isInRange.spec.ts.html#lineNumber30",
    "predicates ::isInRange complains if the value is greater than the upper bound",
    "test"
  ],
  [
    "",
    "test-file/spec/predicates/isInRange.spec.ts.html#lineNumber26",
    "predicates ::isInRange complains if the value is lower than the lower bound",
    "test"
  ],
  [
    "isinteger src/predicates/isinteger.ts~isinteger,isinteger",
    "test-file/spec/predicates/isInteger.spec.ts.html#lineNumber7",
    "predicates ::isInteger",
    "test"
  ],
  [
    "",
    "test-file/spec/predicates/isInteger.spec.ts.html#lineNumber21",
    "predicates ::isInteger ensures that the argument in an integer",
    "test"
  ],
  [
    "islessthan src/predicates/islessthan.ts~islessthan,islessthan",
    "test-file/spec/predicates/isLessThan.spec.ts.html#lineNumber7",
    "predicates ::isLessThan",
    "test"
  ],
  [
    "",
    "test-file/spec/predicates/isLessThan.spec.ts.html#lineNumber24",
    "predicates ::isLessThan complains if the argument is more than a specified number",
    "test"
  ],
  [
    "",
    "test-file/spec/predicates/isLessThan.spec.ts.html#lineNumber21",
    "predicates ::isLessThan ensures that the argument is less than a specified number",
    "test"
  ],
  [
    "islessthanorequalto src/predicates/islessthanorequalto.ts~islessthanorequalto,islessthanorequalto",
    "test-file/spec/predicates/isLessThanOrEqual.spec.ts.html#lineNumber7",
    "predicates ::isLessThanOrEqualTo",
    "test"
  ],
  [
    "",
    "test-file/spec/predicates/isLessThanOrEqual.spec.ts.html#lineNumber25",
    "predicates ::isLessThanOrEqualTo complains if the argument is greater than the upper bound",
    "test"
  ],
  [
    "or src/predicates/or.ts~or,or",
    "test-file/spec/predicates/or.spec.ts.html#lineNumber7",
    "predicates ::or",
    "test"
  ],
  [
    "",
    "test-file/spec/predicates/or.spec.ts.html#lineNumber30",
    "predicates ::or complains if there are no predicates specified",
    "test"
  ],
  [
    "",
    "test-file/spec/predicates/or.spec.ts.html#lineNumber33",
    "predicates ::or concatenates the error messages in a human-friendly way",
    "test"
  ],
  [
    "spec/tinytype.spec.ts",
    "test-file/spec/TinyType.spec.ts.html",
    "spec/TinyType.spec.ts",
    "testFile"
  ],
  [
    "spec/chec.spec.ts",
    "test-file/spec/chec.spec.ts.html",
    "spec/chec.spec.ts",
    "testFile"
  ],
  [
    "spec/json.spec.ts",
    "test-file/spec/json.spec.ts.html",
    "spec/json.spec.ts",
    "testFile"
  ],
  [
    "spec/match.spec.ts",
    "test-file/spec/match.spec.ts.html",
    "spec/match.spec.ts",
    "testFile"
  ],
  [
    "spec/pattern-matching/identitymatcher.spec.ts",
    "test-file/spec/pattern-matching/IdentityMatcher.spec.ts.html",
    "spec/pattern-matching/IdentityMatcher.spec.ts",
    "testFile"
  ],
  [
    "spec/pattern-matching/objectmatcher.spec.ts",
    "test-file/spec/pattern-matching/ObjectMatcher.spec.ts.html",
    "spec/pattern-matching/ObjectMatcher.spec.ts",
    "testFile"
  ],
  [
    "spec/pattern-matching/stringmatcher.spec.ts",
    "test-file/spec/pattern-matching/StringMatcher.spec.ts.html",
    "spec/pattern-matching/StringMatcher.spec.ts",
    "testFile"
  ],
  [
    "spec/pattern-matching/rules/matchesanything.spec.ts",
    "test-file/spec/pattern-matching/rules/MatchesAnything.spec.ts.html",
    "spec/pattern-matching/rules/MatchesAnything.spec.ts",
    "testFile"
  ],
  [
    "spec/predicates/and.spec.ts",
    "test-file/spec/predicates/and.spec.ts.html",
    "spec/predicates/and.spec.ts",
    "testFile"
  ],
  [
    "spec/predicates/haslengthof.spec.ts",
    "test-file/spec/predicates/hasLengthOf.spec.ts.html",
    "spec/predicates/hasLengthOf.spec.ts",
    "testFile"
  ],
  [
    "spec/predicates/isarray.spec.ts",
    "test-file/spec/predicates/isArray.spec.ts.html",
    "spec/predicates/isArray.spec.ts",
    "testFile"
  ],
  [
    "spec/predicates/isdefined.spec.ts",
    "test-file/spec/predicates/isDefined.spec.ts.html",
    "spec/predicates/isDefined.spec.ts",
    "testFile"
  ],
  [
    "spec/predicates/isequalto.spec.ts",
    "test-file/spec/predicates/isEqualTo.spec.ts.html",
    "spec/predicates/isEqualTo.spec.ts",
    "testFile"
  ],
  [
    "spec/predicates/isgreaterthan.spec.ts",
    "test-file/spec/predicates/isGreaterThan.spec.ts.html",
    "spec/predicates/isGreaterThan.spec.ts",
    "testFile"
  ],
  [
    "spec/predicates/isgreaterthanorequalto.spec.ts",
    "test-file/spec/predicates/isGreaterThanOrEqualTo.spec.ts.html",
    "spec/predicates/isGreaterThanOrEqualTo.spec.ts",
    "testFile"
  ],
  [
    "spec/predicates/isinrange.spec.ts",
    "test-file/spec/predicates/isInRange.spec.ts.html",
    "spec/predicates/isInRange.spec.ts",
    "testFile"
  ],
  [
    "spec/predicates/isinteger.spec.ts",
    "test-file/spec/predicates/isInteger.spec.ts.html",
    "spec/predicates/isInteger.spec.ts",
    "testFile"
  ],
  [
    "spec/predicates/islessthan.spec.ts",
    "test-file/spec/predicates/isLessThan.spec.ts.html",
    "spec/predicates/isLessThan.spec.ts",
    "testFile"
  ],
  [
    "spec/predicates/islessthanorequal.spec.ts",
    "test-file/spec/predicates/isLessThanOrEqual.spec.ts.html",
    "spec/predicates/isLessThanOrEqual.spec.ts",
    "testFile"
  ],
  [
    "spec/predicates/or.spec.ts",
    "test-file/spec/predicates/or.spec.ts.html",
    "spec/predicates/or.spec.ts",
    "testFile"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/tinytype.ts",
    "file/src/TinyType.ts.html",
    "src/TinyType.ts",
    "file"
  ],
  [
    "src/tinytype.ts~tinytype#equals",
    "class/src/TinyType.ts~TinyType.html#instance-method-equals",
    "src/TinyType.ts~TinyType#equals",
    "method"
  ],
  [
    "src/tinytype.ts~tinytype#tojson",
    "class/src/TinyType.ts~TinyType.html#instance-method-toJSON",
    "src/TinyType.ts~TinyType#toJSON",
    "method"
  ],
  [
    "src/tinytype.ts~tinytype#tostring",
    "class/src/TinyType.ts~TinyType.html#instance-method-toString",
    "src/TinyType.ts~TinyType#toString",
    "method"
  ],
  [
    "src/check.ts",
    "file/src/check.ts.html",
    "src/check.ts",
    "file"
  ],
  [
    "src/index.ts",
    "file/src/index.ts.html",
    "src/index.ts",
    "file"
  ],
  [
    "src/match.ts",
    "file/src/match.ts.html",
    "src/match.ts",
    "file"
  ],
  [
    "src/pattern-matching/identitymatcher.ts",
    "file/src/pattern-matching/IdentityMatcher.ts.html",
    "src/pattern-matching/IdentityMatcher.ts",
    "file"
  ],
  [
    "src/pattern-matching/objectmatcher.ts",
    "file/src/pattern-matching/ObjectMatcher.ts.html",
    "src/pattern-matching/ObjectMatcher.ts",
    "file"
  ],
  [
    "src/pattern-matching/patternmatcher.ts",
    "file/src/pattern-matching/PatternMatcher.ts.html",
    "src/pattern-matching/PatternMatcher.ts",
    "file"
  ],
  [
    "src/pattern-matching/stringmatcher.ts",
    "file/src/pattern-matching/StringMatcher.ts.html",
    "src/pattern-matching/StringMatcher.ts",
    "file"
  ],
  [
    "src/pattern-matching/index.ts",
    "file/src/pattern-matching/index.ts.html",
    "src/pattern-matching/index.ts",
    "file"
  ],
  [
    "src/pattern-matching/rules/matcherrule.ts",
    "file/src/pattern-matching/rules/MatcherRule.ts.html",
    "src/pattern-matching/rules/MatcherRule.ts",
    "file"
  ],
  [
    "src/pattern-matching/rules/matchesanything.ts",
    "file/src/pattern-matching/rules/MatchesAnything.ts.html",
    "src/pattern-matching/rules/MatchesAnything.ts",
    "file"
  ],
  [
    "src/pattern-matching/rules/matchesequaltinytype.ts",
    "file/src/pattern-matching/rules/MatchesEqualTinyType.ts.html",
    "src/pattern-matching/rules/MatchesEqualTinyType.ts",
    "file"
  ],
  [
    "src/pattern-matching/rules/matchesidentical.ts",
    "file/src/pattern-matching/rules/MatchesIdentical.ts.html",
    "src/pattern-matching/rules/MatchesIdentical.ts",
    "file"
  ],
  [
    "src/pattern-matching/rules/matchesobjectswithcommonprototype.ts",
    "file/src/pattern-matching/rules/MatchesObjectsWithCommonPrototype.ts.html",
    "src/pattern-matching/rules/MatchesObjectsWithCommonPrototype.ts",
    "file"
  ],
  [
    "src/pattern-matching/rules/matchesregexp.ts",
    "file/src/pattern-matching/rules/MatchesRegExp.ts.html",
    "src/pattern-matching/rules/MatchesRegExp.ts",
    "file"
  ],
  [
    "src/pattern-matching/rules/index.ts",
    "file/src/pattern-matching/rules/index.ts.html",
    "src/pattern-matching/rules/index.ts",
    "file"
  ],
  [
    "src/predicates/predicate.ts",
    "file/src/predicates/Predicate.ts.html",
    "src/predicates/Predicate.ts",
    "file"
  ],
  [
    "src/predicates/predicate.ts~failure#constructor",
    "class/src/predicates/Predicate.ts~Failure.html#instance-constructor-constructor",
    "src/predicates/Predicate.ts~Failure#constructor",
    "method"
  ],
  [
    "src/predicates/predicate.ts~failure#description",
    "class/src/predicates/Predicate.ts~Failure.html#instance-member-description",
    "src/predicates/Predicate.ts~Failure#description",
    "member"
  ],
  [
    "src/predicates/predicate.ts~predicate.to",
    "class/src/predicates/Predicate.ts~Predicate.html#static-method-to",
    "src/predicates/Predicate.ts~Predicate.to",
    "method"
  ],
  [
    "src/predicates/predicate.ts~result#constructor",
    "class/src/predicates/Predicate.ts~Result.html#instance-constructor-constructor",
    "src/predicates/Predicate.ts~Result#constructor",
    "method"
  ],
  [
    "src/predicates/predicate.ts~result#value",
    "class/src/predicates/Predicate.ts~Result.html#instance-member-value",
    "src/predicates/Predicate.ts~Result#value",
    "member"
  ],
  [
    "src/predicates/and.ts",
    "file/src/predicates/and.ts.html",
    "src/predicates/and.ts",
    "file"
  ],
  [
    "src/predicates/haslengthof.ts",
    "file/src/predicates/hasLengthOf.ts.html",
    "src/predicates/hasLengthOf.ts",
    "file"
  ],
  [
    "src/predicates/index.ts",
    "file/src/predicates/index.ts.html",
    "src/predicates/index.ts",
    "file"
  ],
  [
    "src/predicates/isarray.ts",
    "file/src/predicates/isArray.ts.html",
    "src/predicates/isArray.ts",
    "file"
  ],
  [
    "src/predicates/isdefined.ts",
    "file/src/predicates/isDefined.ts.html",
    "src/predicates/isDefined.ts",
    "file"
  ],
  [
    "src/predicates/isequalto.ts",
    "file/src/predicates/isEqualTo.ts.html",
    "src/predicates/isEqualTo.ts",
    "file"
  ],
  [
    "src/predicates/isgreaterthan.ts",
    "file/src/predicates/isGreaterThan.ts.html",
    "src/predicates/isGreaterThan.ts",
    "file"
  ],
  [
    "src/predicates/isgreaterthanorequalto.ts",
    "file/src/predicates/isGreaterThanOrEqualTo.ts.html",
    "src/predicates/isGreaterThanOrEqualTo.ts",
    "file"
  ],
  [
    "src/predicates/isinrange.ts",
    "file/src/predicates/isInRange.ts.html",
    "src/predicates/isInRange.ts",
    "file"
  ],
  [
    "src/predicates/isinteger.ts",
    "file/src/predicates/isInteger.ts.html",
    "src/predicates/isInteger.ts",
    "file"
  ],
  [
    "src/predicates/islessthan.ts",
    "file/src/predicates/isLessThan.ts.html",
    "src/predicates/isLessThan.ts",
    "file"
  ],
  [
    "src/predicates/islessthanorequalto.ts",
    "file/src/predicates/isLessThanOrEqualTo.ts.html",
    "src/predicates/isLessThanOrEqualTo.ts",
    "file"
  ],
  [
    "src/predicates/or.ts",
    "file/src/predicates/or.ts.html",
    "src/predicates/or.ts",
    "file"
  ],
  [
    "src/types.ts",
    "file/src/types.ts.html",
    "src/types.ts",
    "file"
  ]
]